# general settings
name: train_DAT_x2__umass_outdoor_flow_COLAB
model_type: DATModel
scale: 2
num_gpu: auto
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    task: SR
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: /content/drive/MyDrive/UpsamplingPaperDatasets/SPlitOutdoorFlowComponentW/train/high_res
    dataroot_lq: /content/drive/MyDrive/UpsamplingPaperDatasets/SPlitOutdoorFlowComponentW/train/low_res
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    lq_patch_size: 128
    use_hflip: True
    use_rot: True
    # data loader
    use_shuffle: True
    num_worker_per_gpu: 1
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    task: SR
    name: Set5
    type: PairedImageDataset
    dataroot_gt: /content/drive/MyDrive/UpsamplingPaperDatasets/SPlitOutdoorFlowComponentW/test/high_res
    dataroot_lq: /content/drive/MyDrive/UpsamplingPaperDatasets/SPlitOutdoorFlowComponentW/test/low_res
    filename_tmpl: '{}'
    io_backend:
      type: disk

# network structures
network_g:
  type: DAT
  upscale: 2
  in_chans: 3
  img_size: 128
  img_range: 1.
  split_size: [8,16]
  depth: [6,6,6,6,6,6]
  embed_dim: 180
  num_heads: [6,6,6,6,6,6]
  expansion_factor: 2
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: /content/drive/MyDrive/UpsamplingPaperDatasets/net_g_2000.pth
  strict_load_g: True
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 25000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  # Physics-Based Losses
  use_umass_loss: False
  use_umass_loss_Vecchiarelli: True
  use_mask: False
  umass_loss_weight: 6
  use_momentum_loss: False
  momentum_loss_weight: 1  # Adjust as necessary
  use_dissipation_loss: False
  dissipation_loss_weight: 5 
  rgb_to_vel: False # Adjust as necessary

# validation settings
val:
  val_freq: !!float 2e3
  save_img: True

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: True
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: True

# logging settings
logger:
  print_freq: 500
  save_checkpoint_freq: !!float 5e2
  use_tb_logger: True
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
