# general settings
name: train_DAT_x4_no_physics_Vector_Sigmoid
model_type: DATModel
scale: 4
num_gpu: auto
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    task: SR
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: /home/vittorio/Scrivania/ResShift_4_scale/data/Vector_Sigmoid_4/train/HR
    dataroot_lq: /home/vittorio/Scrivania/ResShift_4_scale/data/Vector_Sigmoid_4/train/LR_4
    dataroot_vel: /home/vittorio/Scrivania/DAT/datasets/dataset_split_final/train/hr_csv
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 48
    use_hflip: True
    use_rot: True

    # data loader
    use_shuffle: True
    num_worker_per_gpu: 1
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    task: SR
    name: Set5
    type: PairedImageDataset
    dataroot_gt: /home/vittorio/Scrivania/ResShift_4_scale/data/Vector_Sigmoid_4/train/HR
    dataroot_lq: /home/vittorio/Scrivania/ResShift_4_scale/data/Vector_Sigmoid_4/train/LR_4
    dataroot_vel: /home/vittorio/Scrivania/DAT/datasets/dataset_split_final/validation/hr_csv
    filename_tmpl: '{}'
    io_backend:
      type: disk

# network structures
network_g:
  type: DAT
  upscale: 4
  in_chans: 3
  img_size: 12
  img_range: 1.
  split_size: [6,12]
  depth: [6,6,6,6,6,6]
  embed_dim: 180
  num_heads: [6,6,6,6,6,6]
  expansion_factor: 4
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: 
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [20000, 40000, 45000]
    gamma: 0.5

  total_iter: 50000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  
  # Physics-Based Losses
  use_umass_loss: False
  umass_loss_weight: 2 # Adjust as necessary
  use_dissipation_loss: False
  dissipation_loss_weight: 5 
  rgb_to_vel: False # Adjust as necessary

# validation settings
val:
  val_freq: !!float 5e3
  save_img: False

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: True
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: True

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: True
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
